version: '3.8'

services:
  db:
    image: postgres:13
    env_file: 
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - chater

  backend:
    build: ./backend
    env_file: 
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    networks:
      - chater
  
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - db
      - backend
    networks:
      - chater

volumes:
  db_data:

networks:
  chater:
    driver: bridge