version: '3.8'

services:
  db:
    image: postgres:13
    env_file: 
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    env_file: 
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: