// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/login": {
            "post": {
                "description": "Log in a user and return a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth",
                    "V1"
                ],
                "summary": "Log in a user",
                "parameters": [
                    {
                        "description": "User Credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.successResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/register": {
            "post": {
                "description": "Register a new user with username, email, and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth",
                    "V1"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User Data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.successResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/v1/chats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a list of all chats that the authenticated user participates in, including chat members and recent messages.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chats",
                    "V1"
                ],
                "summary": "Get all chats for the authenticated user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.chatsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создаёт новый чат с указанным именем и возвращает его данные",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chats",
                    "V1"
                ],
                "summary": "Создание нового чата",
                "parameters": [
                    {
                        "description": "Данные для создания чата",
                        "name": "chat",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о созданном чате",
                        "schema": {
                            "$ref": "#/definitions/api.chatResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка на сервере",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/v1/chats/{chat_id}/groups": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds a specified group to a chat, requires the user to be authorized",
                "tags": [
                    "Chats",
                    "V1"
                ],
                "summary": "Add a group to a chat",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Chat ID",
                        "name": "chat_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Group to be added to chat",
                        "name": "group",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.groupAddToChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.successResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Chat ID or Request Format",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/v1/chats/{chat_id}/messages": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список всех сообщений в чате по его ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages",
                    "V1"
                ],
                "summary": "Получение сообщений чата",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID чата",
                        "name": "chat_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список сообщений",
                        "schema": {
                            "$ref": "#/definitions/api.messagesResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка в запросе",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка на стороне сервера",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/v1/chats/{chat_id}/ws": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Подключитесь к WebSocket для получения и отправки сообщений в чате в реальном времени.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WebSocket",
                    "Messages",
                    "V1"
                ],
                "summary": "Подключение к WebSocket для чата",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chat ID",
                        "name": "chat_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "WebSocket connection established",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid Chat ID",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to upgrade connection",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/v1/groups": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список всех групп, в которых состоит текущий авторизованный пользователь",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups"
                ],
                "summary": "Получить все группы пользователя",
                "responses": {
                    "200": {
                        "description": "Список групп пользователя",
                        "schema": {
                            "$ref": "#/definitions/api.groupsResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создает новую группу с указанным именем для авторизованного пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups",
                    "V1"
                ],
                "summary": "Создание группы",
                "parameters": [
                    {
                        "description": "Данные для создания группы",
                        "name": "createGroupRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Группа успешно создана",
                        "schema": {
                            "$ref": "#/definitions/api.groupResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка при создании группы",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/v1/groups/{group_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет группу по её идентификатору, если пользователь является её владельцем",
                "tags": [
                    "Groups",
                    "V1"
                ],
                "summary": "Удаление группы",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID группы для удаления",
                        "name": "group_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Группа успешно удалена",
                        "schema": {
                            "$ref": "#/definitions/api.successResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный идентификатор группы",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка при удалении группы",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/v1/groups/{group_id}/users": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Добавляет пользователя в группу по идентификатору группы",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups",
                    "V1"
                ],
                "summary": "Добавление пользователя в группу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID группы",
                        "name": "group_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для добавления пользователя",
                        "name": "addUserToGroupRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.userAddToGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пользователь успешно добавлен в группу",
                        "schema": {
                            "$ref": "#/definitions/api.successResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос или неверный ID группы",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка при добавлении пользователя в группу",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет указанного пользователя из группы, если действие выполняет владелец или администратор группы",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups",
                    "V1"
                ],
                "summary": "Удаление пользователя из группы",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID группы",
                        "name": "group_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ID пользователя для удаления из группы",
                        "name": "userGroupRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.userAddToGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пользователь успешно удалён из группы",
                        "schema": {
                            "$ref": "#/definitions/api.successResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос или неверный ID группы",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка при удалении пользователя из группы",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.chatResponse": {
            "type": "object",
            "properties": {
                "groups": {
                    "description": "Список групп",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.groupResponse"
                    }
                },
                "id": {
                    "description": "Идентификатор чата",
                    "type": "integer"
                },
                "members": {
                    "description": "Список участников чата",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.memberResponse"
                    }
                },
                "messages": {
                    "description": "Последние сообщения чата",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.messageResponse"
                    }
                },
                "name": {
                    "description": "Название чата",
                    "type": "string"
                }
            }
        },
        "api.chatsResponse": {
            "type": "object",
            "properties": {
                "chats": {
                    "description": "Чаты",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.chatResponse"
                    }
                }
            }
        },
        "api.createChatRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "Название чата",
                    "type": "string"
                }
            }
        },
        "api.createGroupRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "groupID": {
                    "type": "integer"
                },
                "name": {
                    "description": "Название группы",
                    "type": "string"
                }
            }
        },
        "api.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "api.groupAddToChatRequest": {
            "type": "object",
            "required": [
                "groupID"
            ],
            "properties": {
                "groupID": {
                    "description": "ID пользователя",
                    "type": "integer"
                }
            }
        },
        "api.groupResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID группы",
                    "type": "integer"
                },
                "isOwner": {
                    "description": "Является ли пользователь владельцем группы",
                    "type": "boolean"
                },
                "name": {
                    "description": "Имя группы",
                    "type": "string"
                }
            }
        },
        "api.groupsResponse": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.groupResponse"
                    }
                }
            }
        },
        "api.loginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "Пароль пользователя",
                    "type": "string"
                },
                "username": {
                    "description": "Имя пользователя",
                    "type": "string"
                }
            }
        },
        "api.memberResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Идентификатор пользователя",
                    "type": "integer"
                },
                "username": {
                    "description": "Имя пользователя",
                    "type": "string"
                }
            }
        },
        "api.messageResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Содержание сообщения",
                    "type": "string"
                },
                "createdAt": {
                    "description": "Время отправки сообщения",
                    "type": "string"
                },
                "id": {
                    "description": "Идентификатор сообщения",
                    "type": "integer"
                },
                "isCurrent": {
                    "description": "Сообщение отправлено текущим пользователем",
                    "type": "boolean"
                },
                "sender": {
                    "description": "Имя отправителя",
                    "type": "string"
                }
            }
        },
        "api.messagesResponse": {
            "type": "object",
            "properties": {
                "messages": {
                    "description": "Сообщения чата",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.messageResponse"
                    }
                }
            }
        },
        "api.registerRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "description": "Емейл пользователя",
                    "type": "string"
                },
                "password": {
                    "description": "Пароль пользователя",
                    "type": "string"
                },
                "username": {
                    "description": "Имя пользователя",
                    "type": "string"
                }
            }
        },
        "api.successResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "api.userAddToGroupRequest": {
            "type": "object",
            "required": [
                "userID"
            ],
            "properties": {
                "userID": {
                    "description": "ID пользователя",
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "token",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:54321",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ChatGPT Backend API",
	Description:      "This is a sample server for a chat backend with JWT authentication.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
